# Site settings
title: Rustoleum
tag_text: rutoleum
description: Rustoleum is a continuous integration system.


# Build settings
markdown: kramdown


exclude: ["README.md"]

highlighter: pygments

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
